name: Static analysis checks and unit tests

on: [pull_request, push, workflow_dispatch]

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run static analysis
      run: prospector -X

    - name: Run unit tests
      run: pytest
